# Generated by Django 4.1.7 on 2023-04-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='anos',
            field=models.DecimalField(decimal_places=0, default=18, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='telefono',
            field=models.DecimalField(decimal_places=0, default=123456789, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='apellidos',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
