# Generated by Django 4.2.1 on 2023-06-02 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.DecimalField(decimal_places=0, max_digits=1)),
                ('apertura', models.TimeField()),
                ('cierre', models.TimeField()),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.centro')),
            ],
        ),
    ]
