# Generated by Django 4.1.7 on 2023-03-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='nombre',
            field=models.CharField(default='rufus', max_length=256),
            preserve_default=False,
        ),
    ]
