# Generated by Django 4.1.7 on 2023-03-16 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_animal_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 3, 16)),
        ),
    ]
