# Generated by Django 4.1.7 on 2023-03-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_adopcion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
