# Generated by Django 4.2.1 on 2023-06-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_prova'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prova',
        ),
    ]
