# Generated by Django 4.2.1 on 2023-06-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_delete_prova'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='abierto',
            field=models.BooleanField(default=False),
        ),
    ]
