# Generated by Django 4.1.7 on 2023-03-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_adopcion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adoptado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
