# Generated by Django 4.1.7 on 2023-04-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_animal_adoptado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='anos',
            field=models.DecimalField(decimal_places=0, default=18, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(default='manuel', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.DecimalField(decimal_places=0, default=654465465, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gato',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.centro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otro',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.centro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.centro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='adresa',
            field=models.CharField(default='c/ carrer random 12', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='apellidos',
            field=models.CharField(default='manuel 2', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
