# Generated by Django 4.2.1 on 2023-06-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_horario_abierto'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.CharField(default='Lunes', max_length=20),
            preserve_default=False,
        ),
    ]
